04/30/2024 15:27:53 - INFO - __main__ - ***** Running training *****
04/30/2024 15:27:53 - INFO - __main__ -   Num examples = 28000
04/30/2024 15:27:53 - INFO - __main__ -   Num Epochs = 300
04/30/2024 15:27:54 - INFO - __main__ -   Instantaneous batch size per device = 64
04/30/2024 15:27:54 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 64
04/30/2024 15:27:54 - INFO - __main__ -   Gradient Accumulation steps = 1
04/30/2024 15:27:54 - INFO - __main__ -   Total optimization steps = 131400
04/30/2024 15:27:54 - INFO - __main__ -   Image path = ddpm-model-mattymchen/celeba-hq-256/Local-celeba-hq-2000-1000-0/FID images
Traceback (most recent call last):
  File "/home/srk1995/anaconda3/envs/ADM/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/srk1995/anaconda3/envs/ADM/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/srk1995/anaconda3/envs/ADM/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/srk1995/anaconda3/envs/ADM/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/srk1995/PycharmProjects/diffusers/examples/unconditional_image_generation/inpaint.py", line 534, in __getitem__
    self.image = torch.tensor(Image.open(self.image_path[idx]))
RuntimeError: Could not infer dtype of PngImageFile
